include(node-js/yarn)

function(FindCMakeJs)
    FindYarn()

    set(options "")
    set(oneValueArgs VERSION)
    set(multiValueArgs "")

    cmake_parse_arguments(FIND_CMAKE_JS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if (NOT FIND_CMAKE_JS_VERSION)
        set(FIND_CMAKE_JS_VERSION "19.0.4")
    endif ()

    function(cmake_js_setup_env var)
        if (NOT ${var})
            yarn_run_output(print_env_value VAR_VALUE ERR_VALUE ${var} ${FIND_CMAKE_JS_VERSION})
            set(${var} ${VAR_VALUE} CACHE INTERNAL "" FORCE)
            message("-- Found ${var}: " ${${var}})
        else()
            message("-- Found ${var}: " ${${var}})
        endif()
    endfunction()

    cmake_js_setup_env(CMAKE_JS_VERSION)
    cmake_js_setup_env(CMAKE_JS_INC)
    cmake_js_setup_env(CMAKE_JS_SRC)
    cmake_js_setup_env(NODE_RUNTIME)
    cmake_js_setup_env(NODE_RUNTIMEVERSION)
    cmake_js_setup_env(NODE_ARCH)
    cmake_js_setup_env(CMAKE_JS_LIB)
    cmake_js_setup_env(NODE_ADDON_API_INCLUDE)
    if (NOT CMAKE_JS_LINKER_FLAGS)
        yarn_run_output(print_env_value CMAKE_JS_LINKER_FLAGS_INTERNAL IGNORED_ERR_VALUE CMAKE_SHARED_LINKER_FLAGS ${FIND_CMAKE_JS_VERSION})
        set(CMAKE_JS_LINKER_FLAGS ${CMAKE_JS_LINKER_FLAGS_INTERNAL} CACHE INTERNAL "" FORCE)
        message("-- Found CMAKE_JS_LINKER_FLAGS: " ${CMAKE_JS_LINKER_FLAGS})
    else()
        message("-- Found CMAKE_JS_LINKER_FLAGS: " ${CMAKE_JS_LINKER_FLAGS})
    endif()
endfunction()
