import argparse
import sys
import pathlib
import os


def main(args):
    parser = argparse.ArgumentParser(
        description='Generates C++ header file from SQL file containing the statement.')
    parser.add_argument('--sql', type=pathlib.Path,
                        help='Source file containing the sql statement')
    parser.add_argument('--out', type=pathlib.Path,
                        help='Destination file which to generate')
    parser.add_argument('--namespace', type=str,
                        help='Namespace in which the statement will be placed')

    args = parser.parse_args(args)

    header = f"""// This file was generated by CMake. Do not edit!
#pragma once

namespace {args.namespace}::sql
{{
  static constexpr const char {os.path.basename(args.sql).partition('.')[0].upper().replace('-', '_')}[] =
"""
    footer = f""";
}}// namespace {args.namespace}::sql
"""

    content = header
    with open(args.sql, 'r') as source:
        for line in source.readlines():
            content += f'    "{line.strip()} "\n'
    content += footer

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, 'w') as dest:
        dest.write(content)


if __name__ == '__main__':
    main(sys.argv[1:])
